### ISSUE TITLE
Tablib fails to convert JSON API response to XLSX file and throws error KeyError:0 

### ISSUE THREAD

**Issue by MarialenaShiamma** [vinayak-mehta/tablib#372]
Hello, I am trying to convert a JSON response I get after calling an API to an excel file. I don't need to add specific headers or get only specific data, I just need everything this call returns.

I managed to make it working when I fetched data from GitLab but after changing my payload to Tfs I get an error which I am not sure what the problem is or how to resolve.

This is my code:

```
    import requests
    import urllib3
    import json
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
    import tablib
    import datetime
    import time
    import os
    
    class gitlab():
    
        def get_closed():
    
            url = "https://IP:443/DefaultCollection/_apis/projects"
    
            payload = {}
    
            querystring = {"api-version":"4.1"}
            
            headers = {
                'Content-Type': "application/json-patch+json",
                'Authorization': "KEY" 
            }
    
            requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
    
            response = requests.request(
                "GET", url, headers=headers, data=payload, params=querystring,  verify=False)
    
            return json.loads(response.text)
    
    
    if __name__ == "__main__":
    
        list_b = gitlab.get_closed() 
    
        print(list_b)
        data = tablib.Dataset()
    
        data.json = json.dumps(list_b)
        
        data_export = data.export('xlsx')
    
        filename = os.path.dirname(os.path.realpath(__file__)) +'/closed_' + str(datetime.date.today()) + '.xlsx'
    
        with open(filename, 'wb') as f: 
            f.write(data_export)  
    
        f.close()
```

Executing with `python script.py` where python's version is `3.7.2` shows the following error:

 ```
   {'count': 1, 'value': [{'id': 'ID', 'name': 'TFS', 'url': 'https://TFS/DefaultCollection/_apis/projects/PROJ', 'state': 'wellFormed', 'revision': 00, 'visibility': 'private'}]}
        
    Traceback (most recent call last):  File ".\gitlab.py", line 94, in <module>    data.json = json.dumps(list_with_bugs, indent=4, ensure_ascii=False)  File "C:\Users\marialena.IRT\AppData\Local\Programs\Python\Python37\lib\site-packages\tablib\formats\_json.py", line 39, in import_set
        dset.dict = json.loads(in_stream)
      File "C:\Users\marialena.IRT\AppData\Local\Programs\Python\Python37\lib\site-packages\tablib\core.py", line 381, in _set_dict
        if isinstance(pickle[0], list):
    KeyError: 0
```

You can see the API response as well in the output. Why is tablib failing to convert to excel?

  [1]: http://docs.python-tablib.org/en/master/api/

**Comment by MarialenaShiamma** [comment]
Please find the Solution [here](https://stackoverflow.com/questions/57167020/tablib-fails-to-convert-json-api-response-to-xlsx-file-and-throws-error-keyerror/57190989#57190989)
